apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mysql-operator.fullname" . }}
  labels:
    {{- include "mysql-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mysql-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: {{ include "mysql-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "mysql-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mysql-operator.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - mysql.middleware.harmonycloud.cn
  resources:
  - mysqlclusters
  - mysqlbackups
  - mysqlbackupschedules
  - mysqlreplicates
  - mysqlclusters/status
  - mysqlreplicates/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims
  - pods/log
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
- apiGroups:
    - "batch"
  resources:
    - jobs
  verbs:
    - get
    - list
    - patch
    - update
    - watch
    - create
