mysqlArgs:
  root_password: "dangerous"
  character_set_server: "utf8mb4"
  max_connections: 600
  wait_timeout: 600
  interactive_timeout: 600
  innodb_buffer_pool_size: 1G
  innodb_flush_log_at_trx_commit: 2
  sql_mode: NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,ERROR_FOR_DIVISION_BY_ZERO
  server_port: 3306

version: 5.7.21
# master-master or master-slave or slave-slave
type: master-master
# semi-sync or group-replication
syncMode: semi-sync
ssh:
  enabled: false

storageSize: 10G
#storageClassName: default

service: {}
#  nodePort: 30066
#  readOnlyNodePort: 30067

businessDeploy: []
# - database: db01
  # pwd: "yourpassword"
  # user: user01

init_at_setup:
  enabled: false
  #init_sql: |-
  #  create database business_ability;

replicaCount: 2

image:
  repository: swr.cn-east-3.myhuaweicloud.com/harmonycloud
  middlewareImageTag: v5.7.21-hc.2
  initImageTag: 1.0.4
  monitorImageTag: v0.12.1
  backupRestoreImageTag: v1.2.0-hc.3
  helmtestImageTag: v1.0.0
  pullPolicy: IfNotPresent
  testImageTag: v0.3

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi


storageProvider: {}
#  minio:
#    endpoint: http://10.1.10.63:30894
#    bucketName: mybucket
#    backupFileName: mysql-example-2020-11-10-150727.gz
#    accessKeyId: minio
#    secretAccessKey: minio123

nodeAffinity: {}

podAntiAffinityTopologKey: "kubernetes.io/hostname"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"
