apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: prometheus-operator-coredns
  labels:
    k8s-app: prometheus-operator-coredns
spec:
  selector:
    k8s-app: kube-dns
  ports:
  - name: metrics
    port: 9153
    targetPort: 9153
    protocol: TCP
