apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackupschedules.mysql.middleware.harmonycloud.cn
  labels:
    MiddlewareCluster: mysqlbackupschedule
    parent: mysqlcluster
spec:
  group: mysql.middleware.harmonycloud.cn
  names:
    kind: MysqlBackupSchedule
    listKind: MysqlBackupScheduleList
    plural: mysqlbackupschedules
    shortNames:
      - mbs
    singular: mysqlbackupschedule
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
