apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.mysql.middleware.harmonycloud.cn
  labels:
    MiddlewareCluster: mysqlbackup
    parent: mysqlcluster
spec:
  group: mysql.middleware.harmonycloud.cn
  names:
    kind: MysqlBackup
    listKind: MysqlBackupList
    plural: mysqlbackups
    shortNames:
      - mb
    singular: mysqlbackup
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
