apiVersion: v1
stringData:
  endpoint: {{ .Release.Name }}.{{ .Release.Namespace }}.svc
  port: "{{ .Values.args.server_port }}"
  username: root
  password: "{{ .Values.args.root_password }}"
kind: Secret
metadata:
  name: {{ .Release.Name }}-credential
  namespace: {{ .Release.Namespace }}
type: Opaque