apiVersion: v1
kind: Service
metadata:
  labels:
    harmonycloud.cn/statefulset: {{ include "mysql.fullname" . }}
    k8s-app: {{ include "mysql.fullname" . }}-exporter
  name: {{ include "mysql.fullname" . }}-mysqld-exporter
spec:
  ports:
    - name: mysqld-exporter
      port: 9104
      protocol: TCP
      targetPort: 9104
  selector:
    app: {{ include "mysql.fullname" . }}
  sessionAffinity: None
  type: ClusterIP