apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: {{ include "alertmanager.fullname" . }}
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    targetPort: web
    nodePort: 31902
  selector:
    alertmanager: alertmanager
    app: alertmanager
  sessionAffinity: ClientIP
